version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: coffee_shop_backend
    ports:
      - "5432:5432"
  app:
    build: .
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:1234@db:5432/coffee_shop_backend
    ports:
      - "8000:8000"
